In [1]:
#!/usr/bin/env python

In [2]:
# -*- coding: utf-8 -*-

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
import tqdm

In [6]:
import torch

In [7]:
import torch.nn.functional as F

In [8]:
from sklearn.ensemble import RandomForestRegressor

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
from sklearn.metrics import r2_score as r2

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
from torch import nn

In [15]:
from torch import optim

In [16]:
from torch.optim import Optimizer

In [17]:
# import python_libs

In [18]:
np.random.seed(42)

In [19]:
# parameters model

In [20]:
torch.manual_seed(42)

In [21]:
# parameters torch model

In [22]:
df = pd.read_csv('recepts.csv')

In [23]:
# download recepts.csv

In [24]:
df.head()

,recipecategory,keywords_1,keywords_2,keywords_3,keywords_4,keywords_5,0,1,2,3,...,reviewcount,calories,fatcontent,cholesterolcontent,sodiumcontent,saturatedfatcontent,fibercontent,sugarcontent,proteincontent,carbohydratecontent
0,26,2,9,3,6,10,2.0,1.0,1.0,4.0,...,4.0,170.9,2.5,8.0,29.8,1.3,3.6,30.2,3.2,37.1
1,15,52,12,4,1,10,3.0,2.0,2.0,1.0,...,1.0,1110.7,58.8,372.8,368.4,16.6,9.0,20.4,63.4,84.4
2,8,10,6,5,3,1,1.0,1.0,1.0,12.0,...,10.0,311.1,0.2,0.0,1.8,0.0,0.4,77.2,0.3,81.5
3,76,17,2,3,14,1,2.0,1.0,2.0,46.0,...,2.0,536.1,24.0,0.0,1558.6,3.8,17.3,32.1,29.3,64.2
4,4,10,7,3,6,19,1.0,1.0,1.0,12.0,...,11.0,103.6,0.4,0.0,959.3,0.1,4.8,17.7,4.3,25.1

In [25]:
# show head() recepts.csv

In [26]:
df.isna().sum()

recipecategory         0
keywords_1             0
keywords_2             0
keywords_3             0
keywords_4             0
keywords_5             0
0                      0
1                      0
2                      0
3                      0
4                      0
5                      0
6                      0
7                      0
8                      0
9                      0
10                     0
11                     0
12                     0
13                     0
14                     0
15                     0
16                     0
17                     0
18                     0
19                     0
20                     0
21                     0
22                     0
23                     0
AggregatedRating       0
reviewcount            0
calories               0
fatcontent             0
cholesterolcontent     0
sodiumcontent          0
saturatedfatcontent    0
fibercontent           0
sugarcontent           0
proteincontent         0
carbohydratecontent    0
dtype: int64

In [27]:
# show isna().sum() recepts.csv

In [28]:
print(df.dtypes)

recipecategory           int64
keywords_1               int64
keywords_2               int64
keywords_3               int64
keywords_4               int64
keywords_5               int64
0                      float64
1                      float64
2                      float64
3                      float64
4                      float64
5                      float64
6                      float64
7                      float64
8                      float64
9                      float64
10                     float64
11                     float64
12                       int64
13                       int64
14                       int64
15                       int64
16                       int64
17                       int64
18                       int64
19                       int64
20                       int64
21                       int64
22                       int64
23                       int64
AggregatedRating       float64
reviewcount            float64
calories               float64
fatcontent             float64
cholesterolcontent     float64
sodiumcontent          float64
saturatedfatcontent    float64
fibercontent           float64
sugarcontent           float64
proteincontent         float64
carbohydratecontent    float64
dtype: object

In [29]:
# show dtypes() recepts.csv

In [30]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 41 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   recipecategory       522517 non-null  int64
 1   keywords_1           522517 non-null  int64
 2   keywords_2           522517 non-null  int64
 3   keywords_3           522517 non-null  int64
 4   keywords_4           522517 non-null  int64
 5   keywords_5           522517 non-null  int64
 6   0                    522517 non-null  float64
 7   1                    522517 non-null  float64
 8   2                    522517 non-null  float64
 9   3                    522517 non-null  float64
 10  4                    522517 non-null  float64
 11  5                    522517 non-null  float64
 12  6                    522517 non-null  float64
 13  7                    522517 non-null  float64
 14  8                    522517 non-null  float64
 15  9                    522517 non-null  float64
 16  10                   522517 non-null  float64
 17  11                   522517 non-null  float64
 18  12                   522517 non-null  int64
 19  13                   522517 non-null  int64
 20  14                   522517 non-null  int64
 21  15                   522517 non-null  int64
 22  16                   522517 non-null  int64
 23  17                   522517 non-null  int64
 24  18                   522517 non-null  int64
 25  19                   522517 non-null  int64
 26  20                   522517 non-null  int64
 27  21                   522517 non-null  int64
 28  22                   522517 non-null  int64
 29  23                   522517 non-null  int64
 30  AggregatedRating     522517 non-null  float64
 31  reviewcount          522517 non-null  float64
 32  calories             522517 non-null  float64
 33  fatcontent           522517 non-null  float64
 34  cholesterolcontent   522517 non-null  float64
 35  sodiumcontent        522517 non-null  float64
 36  saturatedfatcontent  522517 non-null  float64
 37  fibercontent         522517 non-null  float64
 38  sugarcontent         522517 non-null  float64
 39  proteincontent       522517 non-null  float64
 40  carbohydratecontent  522517 non-null  float64
dtypes: float64(23), int64(18)
memory usage: 163.4 MB
None

In [31]:
# show info() recepts.csv

In [32]:
print(df.shape)

(522517, 41)

In [33]:
# show shape() recepts.csv

In [34]:
Y = df['carbohydratecontent']

In [35]:
# show target(Y) recepts.csv

In [36]:
X = df.iloc[:, 0:40]
y = df.iloc[:, 40]

In [37]:
# show target(y)  recepts.csv

In [38]:
X.head()

,recipecategory,keywords_1,keywords_2,keywords_3,keywords_4,keywords_5,0,1,2,3,...,AggregatedRating,reviewcount,calories,fatcontent,cholesterolcontent,sodiumcontent,saturatedfatcontent,fibercontent,sugarcontent,proteincontent
0,26,2,9,3,6,10,2.0,1.0,1.0,4.0,...,4.5,4.0,170.9,2.5,8.0,29.8,1.3,3.6,30.2,3.2
1,15,52,12,4,1,10,3.0,2.0,2.0,1.0,...,3.0,1.0,1110.7,58.8,372.8,368.4,16.6,9.0,20.4,63.4
2,8,10,6,5,3,1,1.0,1.0,1.0,12.0,...,4.5,10.0,311.1,0.2,0.0,1.8,0.0,0.4,77.2,0.3
3,76,17,2,3,14,1,2.0,1.0,2.0,46.0,...,4.5,2.0,536.1,24.0,0.0,1558.6,3.8,17.3,32.1,29.3
4,4,10,7,3,6,19,1.0,1.0,1.0,12.0,...,4.5,11.0,103.6,0.4,0.0,959.3,0.1,4.8,17.7,4.3

In [39]:
# show head() recepts.csv

In [40]:
print(y[:5])

0    37.1
1    84.4
2    81.5
3    64.2
4    25.1
Name: carbohydratecontent, dtype: float64

In [41]:
# show target(y) recepts.csv

In [42]:
print(X.describe())

       recipecategory     keywords_1     keywords_2     keywords_3  \
count   522517.000000  522517.000000  522517.000000  522517.000000
mean        16.309261      16.171478      13.838792       9.577702
std         22.785018      20.981579      17.691402      12.721010
min          1.000000       1.000000       1.000000       1.000000
25%          1.000000       4.000000       3.000000       2.000000
50%          7.000000       8.000000       7.000000       5.000000
75%         21.000000      19.000000      17.000000      10.000000
max        208.000000     195.000000     167.000000     141.000000

          keywords_4     keywords_5              0              1  \
count  522517.000000  522517.000000  522517.000000  522517.000000
mean        9.005596       7.506607       6.531346       6.590226
std        10.283178       7.904510      39.700560      41.644158
min         1.000000       1.000000       0.250000       0.250000
25%         2.000000       2.000000       1.000000       1.000000
50%         5.000000       5.000000       1.000000       1.000000
75%        12.000000      10.000000       2.000000       2.000000
max       122.000000      94.000000    2000.000000    2500.000000

                   2              3  ...  AggregatedRating    reviewcount  \
count  522517.000000  522517.000000  ...     522517.000000  522517.000000
mean        6.468904      14.338731  ...          4.630922       5.375949
std        41.476019      71.710402  ...          0.640397      20.873106
min         0.250000       0.250000  ...          1.000000       1.000000
25%         1.000000       1.000000  ...          4.500000       1.000000
50%         1.000000       2.000000  ...          5.000000       2.000000
75%         2.000000       4.000000  ...          5.000000       4.000000
max      5742.000000    3750.000000  ...          5.000000    3063.000000

            calories     fatcontent  cholesterolcontent  sodiumcontent  \
count  522517.000000  522517.000000       522517.000000   5.225170e+05
mean      484.438580      24.614922           86.487003   7.672639e+02
std      1397.116649     111.485798          301.987009   4.203621e+03
min         0.000000       0.000000            0.000000   0.000000e+00
25%       174.200000       5.600000            3.800000   1.233000e+02
50%       317.100000      13.800000           42.600000   3.533000e+02
75%       529.100000      27.400000          107.900000   7.922000e+02
max    612854.600000   64368.100000       130456.400000   1.246921e+06

       saturatedfatcontent   fibercontent   sugarcontent  proteincontent
count        522517.000000  522517.000000  522517.000000   522517.000000
mean              9.559457       3.843242      21.878254       17.469510
std              46.622621       8.603163     142.620191       40.128837
min               0.000000       0.000000       0.000000        0.000000
25%               1.500000       0.800000       2.500000        3.500000
50%               4.700000       2.200000       6.400000        9.100000
75%              10.800000       4.600000      17.900000       25.000000
max           26740.600000    3012.000000   90682.300000    18396.200000

[8 rows x 40 columns]

In [43]:
# show describe() recepts.csv

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [45]:
# train = 0.7, test = 0.3

In [46]:
scaler = StandardScaler()

In [47]:
# SkLearn.StandardScaler()

In [48]:
X_train = scaler.fit_transform(X_train)

In [49]:
# transform X_train

In [50]:
X_test = scaler.transform(X_test)

In [51]:
# transform X_test

In [52]:
scaler = MinMaxScaler()

In [53]:
# SkLearn.MinMaxScaler()

In [54]:
regressor = RandomForestRegressor(n_estimators=100,
                                      criterion='poisson', max_depth=14, max_features=9, n_jobs = 8, random_state=40)

In [55]:
# n_estimators=100, criterion='poisson', max_depth=14, max_features=9, n_jobs = 8, random_state=40)

In [56]:
regressor.fit(X_train, y_train)

RandomForestRegressor(criterion='poisson', max_depth=14, max_features=9,
                      n_jobs=8, random_state=40)

In [57]:
# SkLearn.RandomForestRegressor()

In [58]:
y_pred = regressor.predict(X_test)

In [59]:
# y_predict X_test

In [60]:
r2(y_test, y_pred)

0.9297972796959653

In [61]:
# SkLearn.R2_score

In [62]:
print(r2(y_test, y_pred))

0.9297972796959653

In [63]:
# SkLearn.R2_score

In [64]:
X_train_scaled = scaler.fit_transform(X_train)

In [65]:
# transform X_train

In [66]:
X_test_scaled = scaler.transform(X_test)

In [67]:
# transform X_test

In [68]:
X_train_tensor = torch.Tensor(np.array(X_train_scaled))

In [69]:
# transform tensor X_train

In [70]:
X_test_tensor = torch.Tensor(np.array(X_test_scaled))

In [71]:
# transform tensor X_test

In [72]:
y_train_tensor = torch.Tensor(np.array(y_train))

In [73]:
# transform tensor y_train

In [74]:
y_test_tensor = torch.Tensor(np.array(y_test))

In [75]:
# transform tensor y_test

In [76]:
n_data, n_features = X_train_tensor.shape

In [77]:
# show shape() n_data, n_features

In [78]:
print(n_data)

365761

In [79]:
# show shape() n_data

In [80]:
print(n_features)

40

In [81]:
# show shape() n_features

In [82]:
def loss(mean, target):
    """function loss"""
    return mean(F.l1_loss(input, target, reduction="none") / target) * 100

In [83]:
# function loss

In [84]:
loss_func = F.mse_loss

In [85]:
# loss_func()

In [86]:
metrics_func_1 = [loss_func, loss]

In [87]:
# loss()

In [88]:
metrics_name = ["MSE", "LOSS"]

In [89]:
# loss

In [90]:
def print_metrics(models, train_data, test_data, models_name):
    """function print_metrics"""
    results = np.ones(2 * len(models), len(metrics_func_1))
    models_name = []
    for model in models_name:
        models_name.extend([model + "Train", model + "Test"])
    for row, sample in enumerate([train_data, test_data]):
        results[row + sample * 2] = evaluate(models, metrics_func_1, sample[0], sample[1])
        results = pd.DataFrame(results, columns=metrics_name, index=models_name)
        return results

In [91]:
# function loss

In [92]:
train_data_1 = (X_train_tensor, y_train_tensor)

In [93]:
# train_data_1

In [94]:
test_data_1 = (X_test_tensor, y_test_tensor)

In [95]:
# test_data_1

In [96]:
model_lr_sklearn = LinearRegression()

In [97]:
# SkLearn.LinearRegression()

In [98]:
model_lr_sklearn.fit(X_train_scaled, y_train)

LinearRegression()

In [99]:
# SkLearn.LinearRegression()

In [100]:
model_1 = [model_lr_sklearn.predict]

In [101]:
# model_lr_sklearn.predict

In [102]:
metrics_name = ["MSE", "LOSS"]

In [103]:
# loss()

In [104]:
models_name_1 = ["LOSS"]

In [105]:
# loss()

In [106]:
model_lr = nn.Sequential(
    nn.Linear(in_features=n_features,
    out_features=1))

In [107]:
# torch model_lr

In [108]:
print(model_lr)

Sequential(
  (0): Linear(in_features=40, out_features=1, bias=True)
)

In [109]:
# torch model_lr

In [110]:
metrics_name_1 = torch.nn.MSELoss()

In [111]:
# torch.nn.MSELoss()

In [112]:
Optimizer = optim.SGD(params=model_lr.parameters(), lr=0.001)

In [113]:
# torch optimizer model_lr

In [114]:
BATCH_SIZE_LR = 16

In [115]:
# torch batch

In [116]:
EPOCHS_LR = 1000

In [117]:
# torch epochs

In [118]:
for epoch in tqdm.trange(EPOCHS_LR):
    for i in range((n_data - 1) // BATCH_SIZE_LR + 1):
        start_i = i * BATCH_SIZE_LR
        end_i = start_i + BATCH_SIZE_LR
        Xb = X_train_tensor[start_i: end_i]
        yb = y_train_tensor[start_i: end_i]
        pred = yb
        loss_1 = loss_func(pred, yb + 1)

100%|███████████████████████████████████████| 1000/1000 [06:46<00:00,  2.46it/s]

In [119]:
# for epoch in tqdm.trange(EPOCHS_LR)

In [120]:
print(X_test)

[[ 2.14267765  0.039095    0.79884574 ...  0.89335901 -0.10884598
  -0.14702155]
 [ 0.64735879 -0.48534494 -0.66910215 ...  0.62880074  0.01611935
  -0.11988125]
 [-0.67204021  3.51946916 -0.21742588 ... -0.37652072 -0.03241087
  -0.37545239]
 ...
 [ 0.11959919 -0.67605037 -0.49972355 ... -0.3024444  -0.0591025
  -0.35283548]
 [-0.18826058 -0.48534494 -0.21742588 ... -0.39768538 -0.13371772
   1.35700334]
 [ 0.16357915 -0.67605037 -0.49972355 ... -0.37652072 -0.09671342
  -0.36188224]]

In [121]:
# X_test

In [122]:
print(y_test)

360511    39.3
392362    85.1
441510    20.2
106802    42.7
53         3.5
          ...
326281    20.1
64228      6.7
340331    20.1
1465       0.9
40621      9.8
Name: carbohydratecontent, Length: 156756, dtype: float64

In [123]:
# y_test

In [124]:
X = torch.randn(BATCH_SIZE_LR, 40)

In [125]:
# torch.randn()

In [126]:
y = torch.Tensor([[1.0], [0.0], [0.0], [1.0], [1.0],
    [1.0], [0.0], [0.0], [1.0], [1.0],
    [1.0], [0.0], [0.0], [1.0], [1.0],
    [1.0]])

In [127]:
# torch tensor

In [128]:
for epoch in range(1000):
    y_pred = model_lr(X)
    loss = metrics_name_1(y_pred, y)
    print('epoch: ', epoch,' loss: ', loss.item())
    Optimizer.zero_grad()
    loss.backward()
    Optimizer.step()

epoch:  0  loss:  0.8530113697052002
epoch:  1  loss:  0.844667375087738
epoch:  2  loss:  0.8364248871803284
epoch:  3  loss:  0.8282825350761414
epoch:  4  loss:  0.8202389478683472
epoch:  5  loss:  0.8122928142547607
epoch:  6  loss:  0.8044425845146179
epoch:  7  loss:  0.7966870069503784
epoch:  8  loss:  0.7890247106552124
epoch:  9  loss:  0.7814543843269348
epoch:  10  loss:  0.7739750146865845
epoch:  11  loss:  0.7665848731994629
epoch:  12  loss:  0.7592829465866089
epoch:  13  loss:  0.7520681023597717
epoch:  14  loss:  0.7449389696121216
epoch:  15  loss:  0.737894594669342
epoch:  16  loss:  0.730933427810669
epoch:  17  loss:  0.7240545153617859
epoch:  18  loss:  0.7172568440437317
epoch:  19  loss:  0.7105392813682556
epoch:  20  loss:  0.7039003968238831
epoch:  21  loss:  0.6973394155502319
epoch:  22  loss:  0.6908552050590515
epoch:  23  loss:  0.6844468116760254
epoch:  24  loss:  0.6781128644943237
epoch:  25  loss:  0.6718526482582092
epoch:  26  loss:  0.6656651496887207
epoch:  27  loss:  0.6595491766929626
epoch:  28  loss:  0.653503954410553
epoch:  29  loss:  0.6475284695625305
epoch:  30  loss:  0.6416217088699341
epoch:  31  loss:  0.6357826590538025
epoch:  32  loss:  0.630010724067688
epoch:  33  loss:  0.6243047118186951
epoch:  34  loss:  0.6186637878417969
epoch:  35  loss:  0.6130872368812561
epoch:  36  loss:  0.6075738668441772
epoch:  37  loss:  0.6021230816841125
epoch:  38  loss:  0.5967340469360352
epoch:  39  loss:  0.5914058685302734
epoch:  40  loss:  0.586137592792511
epoch:  41  loss:  0.5809287428855896
epoch:  42  loss:  0.5757782459259033
epoch:  43  loss:  0.5706855058670044
epoch:  44  loss:  0.5656495094299316
epoch:  45  loss:  0.5606698989868164
epoch:  46  loss:  0.5557454824447632
epoch:  47  loss:  0.5508758425712585
epoch:  48  loss:  0.5460601449012756
epoch:  49  loss:  0.5412977337837219
epoch:  50  loss:  0.5365877747535706
epoch:  51  loss:  0.5319297313690186
epoch:  52  loss:  0.5273228287696838
epoch:  53  loss:  0.5227664113044739
epoch:  54  loss:  0.5182598829269409
epoch:  55  loss:  0.5138024687767029
epoch:  56  loss:  0.5093936324119568
epoch:  57  loss:  0.5050326585769653
epoch:  58  loss:  0.5007190108299255
epoch:  59  loss:  0.49645206332206726
epoch:  60  loss:  0.49223122000694275
epoch:  61  loss:  0.4880557656288147
epoch:  62  loss:  0.4839252233505249
epoch:  63  loss:  0.4798389971256256
epoch:  64  loss:  0.47579652070999146
epoch:  65  loss:  0.4717971980571747
epoch:  66  loss:  0.4678404927253723
epoch:  67  loss:  0.46392586827278137
epoch:  68  loss:  0.46005281805992126
epoch:  69  loss:  0.45622071623802185
epoch:  70  loss:  0.4524291753768921
epoch:  71  loss:  0.4486774802207947
epoch:  72  loss:  0.4449653923511505
epoch:  73  loss:  0.4412921369075775
epoch:  74  loss:  0.43765735626220703
epoch:  75  loss:  0.43406060338020325
epoch:  76  loss:  0.43050137162208557
epoch:  77  loss:  0.4269791543483734
epoch:  78  loss:  0.4234934449195862
epoch:  79  loss:  0.4200439155101776
epoch:  80  loss:  0.41662999987602234
epoch:  81  loss:  0.41325128078460693
epoch:  82  loss:  0.40990737080574036
epoch:  83  loss:  0.4065977931022644
epoch:  84  loss:  0.40332216024398804
epoch:  85  loss:  0.4000799059867859
epoch:  86  loss:  0.39687076210975647
epoch:  87  loss:  0.39369431138038635
epoch:  88  loss:  0.3905501067638397
epoch:  89  loss:  0.3874377906322479
epoch:  90  loss:  0.38435688614845276
epoch:  91  loss:  0.38130709528923035
epoch:  92  loss:  0.3782879710197449
epoch:  93  loss:  0.37529921531677246
epoch:  94  loss:  0.3723403513431549
epoch:  95  loss:  0.3694111704826355
epoch:  96  loss:  0.36651113629341125
epoch:  97  loss:  0.36364004015922546
epoch:  98  loss:  0.3607974648475647
epoch:  99  loss:  0.3579829931259155
epoch:  100  loss:  0.355196475982666
epoch:  101  loss:  0.3524373471736908
epoch:  102  loss:  0.3497055172920227
epoch:  103  loss:  0.3470004200935364
epoch:  104  loss:  0.3443218171596527
epoch:  105  loss:  0.34166955947875977
epoch:  106  loss:  0.3390430808067322
epoch:  107  loss:  0.336442232131958
epoch:  108  loss:  0.3338666260242462
epoch:  109  loss:  0.3313160240650177
epoch:  110  loss:  0.3287901282310486
epoch:  111  loss:  0.3262885808944702
epoch:  112  loss:  0.3238111436367035
epoch:  113  loss:  0.32135751843452454
epoch:  114  loss:  0.31892746686935425
epoch:  115  loss:  0.31652069091796875
epoch:  116  loss:  0.3141368329524994
epoch:  117  loss:  0.31177574396133423
epoch:  118  loss:  0.3094370663166046
epoch:  119  loss:  0.30712059140205383
epoch:  120  loss:  0.3048260807991028
epoch:  121  loss:  0.3025532364845276
epoch:  122  loss:  0.30030182003974915
epoch:  123  loss:  0.29807156324386597
epoch:  124  loss:  0.2958622872829437
epoch:  125  loss:  0.29367366433143616
epoch:  126  loss:  0.29150551557540894
epoch:  127  loss:  0.28935757279396057
epoch:  128  loss:  0.28722965717315674
epoch:  129  loss:  0.2851214110851288
epoch:  130  loss:  0.2830328345298767
epoch:  131  loss:  0.2809634804725647
epoch:  132  loss:  0.2789132595062256
epoch:  133  loss:  0.2768819034099579
epoch:  134  loss:  0.2748692035675049
epoch:  135  loss:  0.27287495136260986
epoch:  136  loss:  0.2708989679813385
epoch:  137  loss:  0.2689410150051117
epoch:  138  loss:  0.2670009136199951
epoch:  139  loss:  0.26507845520973206
epoch:  140  loss:  0.263173371553421
epoch:  141  loss:  0.26128557324409485
epoch:  142  loss:  0.2594148516654968
epoch:  143  loss:  0.25756096839904785
epoch:  144  loss:  0.2557237446308136
epoch:  145  loss:  0.25390303134918213
epoch:  146  loss:  0.2520986795425415
epoch:  147  loss:  0.25031036138534546
epoch:  148  loss:  0.2485380470752716
epoch:  149  loss:  0.24678151309490204
epoch:  150  loss:  0.24504058063030243
epoch:  151  loss:  0.24331508576869965
epoch:  152  loss:  0.24160486459732056
epoch:  153  loss:  0.23990970849990845
epoch:  154  loss:  0.23822952806949615
epoch:  155  loss:  0.2365640550851822
epoch:  156  loss:  0.23491324484348297
epoch:  157  loss:  0.23327691853046417
epoch:  158  loss:  0.23165485262870789
epoch:  159  loss:  0.23004691302776337
epoch:  160  loss:  0.22845298051834106
epoch:  161  loss:  0.22687289118766785
epoch:  162  loss:  0.2253064662218094
epoch:  163  loss:  0.2237536609172821
epoch:  164  loss:  0.2222142219543457
epoch:  165  loss:  0.22068803012371063
epoch:  166  loss:  0.21917499601840973
epoch:  167  loss:  0.21767489612102509
epoch:  168  loss:  0.21618768572807312
epoch:  169  loss:  0.21471315622329712
epoch:  170  loss:  0.21325120329856873
epoch:  171  loss:  0.21180172264575958
epoch:  172  loss:  0.21036453545093536
epoch:  173  loss:  0.20893950760364532
epoch:  174  loss:  0.2075265645980835
epoch:  175  loss:  0.20612555742263794
epoch:  176  loss:  0.20473633706569672
epoch:  177  loss:  0.20335881412029266
epoch:  178  loss:  0.20199283957481384
epoch:  179  loss:  0.2006383091211319
epoch:  180  loss:  0.19929513335227966
epoch:  181  loss:  0.1979631632566452
epoch:  182  loss:  0.19664227962493896
epoch:  183  loss:  0.1953323632478714
epoch:  184  loss:  0.19403333961963654
epoch:  185  loss:  0.19274505972862244
epoch:  186  loss:  0.19146741926670074
epoch:  187  loss:  0.1902003437280655
epoch:  188  loss:  0.18894366919994354
epoch:  189  loss:  0.18769733607769012
epoch:  190  loss:  0.18646124005317688
epoch:  191  loss:  0.18523524701595306
epoch:  192  loss:  0.1840192824602127
epoch:  193  loss:  0.18281322717666626
epoch:  194  loss:  0.18161697685718536
epoch:  195  loss:  0.18043048679828644
epoch:  196  loss:  0.17925359308719635
epoch:  197  loss:  0.17808623611927032
epoch:  198  loss:  0.17692831158638
epoch:  199  loss:  0.17577970027923584
epoch:  200  loss:  0.17464037239551544
epoch:  201  loss:  0.17351016402244568
epoch:  202  loss:  0.17238903045654297
epoch:  203  loss:  0.17127689719200134
epoch:  204  loss:  0.17017363011837006
epoch:  205  loss:  0.16907916963100433
epoch:  206  loss:  0.16799339652061462
epoch:  207  loss:  0.16691631078720093
epoch:  208  loss:  0.1658477485179901
epoch:  209  loss:  0.16478762030601501
epoch:  210  loss:  0.16373588144779205
epoch:  211  loss:  0.16269247233867645
epoch:  212  loss:  0.16165724396705627
epoch:  213  loss:  0.16063019633293152
epoch:  214  loss:  0.15961118042469025
epoch:  215  loss:  0.15860016644001007
epoch:  216  loss:  0.15759703516960144
epoch:  217  loss:  0.15660174190998077
epoch:  218  loss:  0.1556142270565033
epoch:  219  loss:  0.15463435649871826
epoch:  220  loss:  0.15366217494010925
epoch:  221  loss:  0.15269742906093597
epoch:  222  loss:  0.1517402082681656
epoch:  223  loss:  0.15079039335250854
epoch:  224  loss:  0.1498478800058365
epoch:  225  loss:  0.14891260862350464
epoch:  226  loss:  0.1479845494031906
epoch:  227  loss:  0.14706359803676605
epoch:  228  loss:  0.14614972472190857
epoch:  229  loss:  0.1452428251504898
epoch:  230  loss:  0.14434285461902618
epoch:  231  loss:  0.14344975352287292
epoch:  232  loss:  0.14256341755390167
epoch:  233  loss:  0.14168384671211243
epoch:  234  loss:  0.14081093668937683
epoch:  235  loss:  0.13994461297988892
epoch:  236  loss:  0.13908489048480988
epoch:  237  loss:  0.13823162019252777
epoch:  238  loss:  0.13738477230072021
epoch:  239  loss:  0.13654430210590363
epoch:  240  loss:  0.13571013510227203
epoch:  241  loss:  0.13488225638866425
epoch:  242  loss:  0.13406051695346832
epoch:  243  loss:  0.13324496150016785
epoch:  244  loss:  0.13243548572063446
epoch:  245  loss:  0.1316320300102234
epoch:  246  loss:  0.13083454966545105
epoch:  247  loss:  0.13004301488399506
epoch:  248  loss:  0.12925730645656586
epoch:  249  loss:  0.12847745418548584
epoch:  250  loss:  0.12770333886146545
epoch:  251  loss:  0.1269349604845047
epoch:  252  loss:  0.12617221474647522
epoch:  253  loss:  0.12541508674621582
epoch:  254  loss:  0.12466353178024292
epoch:  255  loss:  0.12391746044158936
epoch:  256  loss:  0.12317687273025513
epoch:  257  loss:  0.12244169414043427
epoch:  258  loss:  0.12171190232038498
epoch:  259  loss:  0.1209874078631401
epoch:  260  loss:  0.12026817351579666
epoch:  261  loss:  0.11955418437719345
epoch:  262  loss:  0.1188453733921051
epoch:  263  loss:  0.11814171075820923
epoch:  264  loss:  0.11744309961795807
epoch:  265  loss:  0.11674956977367401
epoch:  266  loss:  0.1160610094666481
epoch:  267  loss:  0.11537743359804153
epoch:  268  loss:  0.11469876021146774
epoch:  269  loss:  0.11402496695518494
epoch:  270  loss:  0.11335599422454834
epoch:  271  loss:  0.11269180476665497
epoch:  272  loss:  0.11203236877918243
epoch:  273  loss:  0.11137765645980835
epoch:  274  loss:  0.11072757840156555
epoch:  275  loss:  0.11008217930793762
epoch:  276  loss:  0.10944131761789322
epoch:  277  loss:  0.10880502313375473
epoch:  278  loss:  0.10817322134971619
epoch:  279  loss:  0.10754591226577759
epoch:  280  loss:  0.10692303627729416
epoch:  281  loss:  0.10630453377962112
epoch:  282  loss:  0.10569038987159729
epoch:  283  loss:  0.10508058220148087
epoch:  284  loss:  0.10447505861520767
epoch:  285  loss:  0.10387375950813293
epoch:  286  loss:  0.10327672213315964
epoch:  287  loss:  0.10268383473157883
epoch:  288  loss:  0.10209508240222931
epoch:  289  loss:  0.10151045024394989
epoch:  290  loss:  0.1009298786520958
epoch:  291  loss:  0.10035335272550583
epoch:  292  loss:  0.0997808426618576
epoch:  293  loss:  0.09921231120824814
epoch:  294  loss:  0.09864769130945206
epoch:  295  loss:  0.09808701276779175
epoch:  296  loss:  0.09753017872571945
epoch:  297  loss:  0.09697721153497696
epoch:  298  loss:  0.0964280441403389
epoch:  299  loss:  0.09588264673948288
epoch:  300  loss:  0.09534101188182831
epoch:  301  loss:  0.0948030948638916
epoch:  302  loss:  0.09426886588335037
epoch:  303  loss:  0.09373830258846283
epoch:  304  loss:  0.09321136772632599
epoch:  305  loss:  0.09268801659345627
epoch:  306  loss:  0.09216824173927307
epoch:  307  loss:  0.09165199846029282
epoch:  308  loss:  0.0911393016576767
epoch:  309  loss:  0.09063006192445755
epoch:  310  loss:  0.09012427181005478
epoch:  311  loss:  0.08962193131446838
epoch:  312  loss:  0.08912297338247299
epoch:  313  loss:  0.0886274129152298
epoch:  314  loss:  0.08813517540693283
epoch:  315  loss:  0.08764626085758209
epoch:  316  loss:  0.08716065436601639
epoch:  317  loss:  0.08667828142642975
epoch:  318  loss:  0.08619918674230576
epoch:  319  loss:  0.08572328090667725
epoch:  320  loss:  0.08525057882070541
epoch:  321  loss:  0.08478102087974548
epoch:  322  loss:  0.08431461453437805
epoch:  323  loss:  0.08385131508111954
epoch:  324  loss:  0.08339112251996994
epoch:  325  loss:  0.08293397724628448
epoch:  326  loss:  0.08247987926006317
epoch:  327  loss:  0.08202880620956421
epoch:  328  loss:  0.08158072829246521
epoch:  329  loss:  0.08113560825586319
epoch:  330  loss:  0.08069343864917755
epoch:  331  loss:  0.0802542045712471
epoch:  332  loss:  0.07981784641742706
epoch:  333  loss:  0.07938437163829803
epoch:  334  loss:  0.07895377278327942
epoch:  335  loss:  0.07852599024772644
epoch:  336  loss:  0.07810103893280029
epoch:  337  loss:  0.0776788741350174
epoch:  338  loss:  0.07725944370031357
epoch:  339  loss:  0.07684280723333359
epoch:  340  loss:  0.07642887532711029
epoch:  341  loss:  0.07601764053106308
epoch:  342  loss:  0.07560908794403076
epoch:  343  loss:  0.07520321011543274
epoch:  344  loss:  0.07479996979236603
epoch:  345  loss:  0.07439935952425003
epoch:  346  loss:  0.07400135695934296
epoch:  347  loss:  0.07360592484474182
epoch:  348  loss:  0.07321307808160782
epoch:  349  loss:  0.07282275706529617
epoch:  350  loss:  0.07243494689464569
epoch:  351  loss:  0.07204966992139816
epoch:  352  loss:  0.07166687399148941
epoch:  353  loss:  0.07128655165433884
epoch:  354  loss:  0.07090865075588226
epoch:  355  loss:  0.07053319364786148
epoch:  356  loss:  0.0701601579785347
epoch:  357  loss:  0.06978950649499893
epoch:  358  loss:  0.06942124664783478
epoch:  359  loss:  0.06905533373355865
epoch:  360  loss:  0.06869175285100937
epoch:  361  loss:  0.06833050400018692
epoch:  362  loss:  0.06797156482934952
epoch:  363  loss:  0.06761489808559418
epoch:  364  loss:  0.06726052612066269
epoch:  365  loss:  0.06690838932991028
epoch:  366  loss:  0.06655849516391754
epoch:  367  loss:  0.06621082872152328
epoch:  368  loss:  0.06586537510156631
epoch:  369  loss:  0.06552209705114365
epoch:  370  loss:  0.06518097966909409
epoch:  371  loss:  0.06484205275774002
epoch:  372  loss:  0.06450523436069489
epoch:  373  loss:  0.06417056173086166
epoch:  374  loss:  0.06383797526359558
epoch:  375  loss:  0.06350751221179962
epoch:  376  loss:  0.06317910552024841
epoch:  377  loss:  0.06285277009010315
epoch:  378  loss:  0.06252848356962204
epoch:  379  loss:  0.06220622360706329
epoch:  380  loss:  0.06188597530126572
epoch:  381  loss:  0.061567746102809906
epoch:  382  loss:  0.061251506209373474
epoch:  383  loss:  0.06093724071979523
epoch:  384  loss:  0.06062491238117218
epoch:  385  loss:  0.06031455472111702
epoch:  386  loss:  0.06000612676143646
epoch:  387  loss:  0.05969959497451782
epoch:  388  loss:  0.05939498916268349
epoch:  389  loss:  0.05909224599599838
epoch:  390  loss:  0.05879141762852669
epoch:  391  loss:  0.058492425829172134
epoch:  392  loss:  0.05819527804851532
epoch:  393  loss:  0.057899974286556244
epoch:  394  loss:  0.057606492191553116
epoch:  395  loss:  0.05731482803821564
epoch:  396  loss:  0.057024966925382614
epoch:  397  loss:  0.05673688277602196
epoch:  398  loss:  0.05645056441426277
epoch:  399  loss:  0.05616599693894386
epoch:  400  loss:  0.05588318780064583
epoch:  401  loss:  0.05560211092233658
epoch:  402  loss:  0.055322758853435516
epoch:  403  loss:  0.05504511669278145
epoch:  404  loss:  0.05476916581392288
epoch:  405  loss:  0.054494913667440414
epoch:  406  loss:  0.05422231927514076
epoch:  407  loss:  0.05395137891173363
epoch:  408  loss:  0.053682100027799606
epoch:  409  loss:  0.05341446399688721
epoch:  410  loss:  0.05314844101667404
epoch:  411  loss:  0.052884042263031006
epoch:  412  loss:  0.05262124165892601
epoch:  413  loss:  0.052360039204359055
epoch:  414  loss:  0.05210040509700775
epoch:  415  loss:  0.051842354238033295
epoch:  416  loss:  0.051585860550403595
epoch:  417  loss:  0.05133091285824776
epoch:  418  loss:  0.05107749253511429
epoch:  419  loss:  0.05082561448216438
epoch:  420  loss:  0.05057523772120476
epoch:  421  loss:  0.050326380878686905
epoch:  422  loss:  0.05007901415228844
epoch:  423  loss:  0.04983312264084816
epoch:  424  loss:  0.049588702619075775
epoch:  425  loss:  0.049345772713422775
epoch:  426  loss:  0.049104273319244385
epoch:  427  loss:  0.04886423051357269
epoch:  428  loss:  0.04862561449408531
epoch:  429  loss:  0.04838842153549194
epoch:  430  loss:  0.04815263673663139
epoch:  431  loss:  0.04791827127337456
epoch:  432  loss:  0.04768529534339905
epoch:  433  loss:  0.047453705221414566
epoch:  434  loss:  0.04722347855567932
epoch:  435  loss:  0.04699462652206421
epoch:  436  loss:  0.046767134219408035
epoch:  437  loss:  0.04654097557067871
epoch:  438  loss:  0.04631616920232773
epoch:  439  loss:  0.046092692762613297
epoch:  440  loss:  0.04587052762508392
epoch:  441  loss:  0.045649681240320206
epoch:  442  loss:  0.045430127531290054
epoch:  443  loss:  0.04521186649799347
epoch:  444  loss:  0.044994913041591644
epoch:  445  loss:  0.0447792150080204
epoch:  446  loss:  0.044564783573150635
epoch:  447  loss:  0.04435161128640175
epoch:  448  loss:  0.04413968697190285
epoch:  449  loss:  0.04392901062965393
epoch:  450  loss:  0.04371955990791321
epoch:  451  loss:  0.04351134970784187
epoch:  452  loss:  0.043304335325956345
epoch:  453  loss:  0.04309853911399841
epoch:  454  loss:  0.04289393126964569
epoch:  455  loss:  0.04269053414463997
epoch:  456  loss:  0.04248829931020737
epoch:  457  loss:  0.042287249118089676
epoch:  458  loss:  0.0420873761177063
epoch:  459  loss:  0.04188865050673485
epoch:  460  loss:  0.04169108718633652
epoch:  461  loss:  0.04149467125535011
epoch:  462  loss:  0.041299380362033844
epoch:  463  loss:  0.0411052368581295
epoch:  464  loss:  0.0409121960401535
epoch:  465  loss:  0.040720272809267044
epoch:  466  loss:  0.040529463440179825
epoch:  467  loss:  0.040339745581150055
epoch:  468  loss:  0.04015112668275833
epoch:  469  loss:  0.03996358439326286
epoch:  470  loss:  0.039777133613824844
epoch:  471  loss:  0.03959175571799278
epoch:  472  loss:  0.03940742835402489
epoch:  473  loss:  0.039224158972501755
epoch:  474  loss:  0.03904194012284279
epoch:  475  loss:  0.038860756903886795
epoch:  476  loss:  0.038680627942085266
epoch:  477  loss:  0.03850151225924492
epoch:  478  loss:  0.03832342475652695
epoch:  479  loss:  0.03814634680747986
epoch:  480  loss:  0.03797028213739395
epoch:  481  loss:  0.03779522702097893
epoch:  482  loss:  0.0376211442053318
epoch:  483  loss:  0.03744806349277496
epoch:  484  loss:  0.03727596625685692
epoch:  485  loss:  0.03710484877228737
epoch:  486  loss:  0.03693469613790512
epoch:  487  loss:  0.03676550090312958
epoch:  488  loss:  0.036597274243831635
epoch:  489  loss:  0.036430004984140396
epoch:  490  loss:  0.03626366704702377
epoch:  491  loss:  0.036098264157772064
epoch:  492  loss:  0.035933803766965866
epoch:  493  loss:  0.03577026352286339
epoch:  494  loss:  0.03560763597488403
epoch:  495  loss:  0.035445939749479294
epoch:  496  loss:  0.03528513386845589
epoch:  497  loss:  0.0351252406835556
epoch:  498  loss:  0.03496624156832695
epoch:  499  loss:  0.03480812907218933
epoch:  500  loss:  0.034650906920433044
epoch:  501  loss:  0.03449456766247749
epoch:  502  loss:  0.03433908894658089
epoch:  503  loss:  0.034184493124485016
epoch:  504  loss:  0.034030746668577194

In [129]:
# for epoch in range(1000)

In [130]:
def train(model_lr, loss_fn, optimizer):
    """function train"""
    size = len(X_train_tensor)
    model_lr.train()
    for batch_size_lr in range(1000):
        y_pred_1 = model_lr(X)
        loss = loss_fn(y_pred_1, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if BATCH_SIZE_LR % 16 == 0:
            loss_2 = loss.item(), BATCH_SIZE_LR * len(X)
            print(f'loss: {loss_2}')

In [131]:
# function train

In [132]:
def test(model_lr, loss_fn):
    """function test"""
    size = len(X_train_tensor)
    num_batches = size
    model_lr.eval()
    test_loss = 0
    with torch.no_grad():
        for batch_size_lr in range(1000):
            y_pred_2 = model_lr(X)
            test_loss += loss_fn(y_pred_2, y).item()
            test_loss /= num_batches
            print(f'Test loss: {test_loss}')

In [133]:
# function test

In [134]:
loss_fn = nn.CrossEntropyLoss()

In [135]:
# loss_fn()

In [136]:
# for epoch in range(EPOCHS_LR)

In [137]:
# google-chrome-stable 126 -error memory chrome

In [138]:
# results(for epoch in range(EPOCHS_LR)): to see python_script.py

In [139]:
with torch.no_grad():
    print(model_lr(X_test_tensor[-1:]))

tensor([[0.2285]])

In [140]:
# X_test_tensor[-1:]

In [141]:
torch.save(model_lr, "lr.pth")

In [142]:
# torch.save(model_lr)

In [143]:
model_lr_1 = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=16),
    nn.ReLU(),
    nn.Linear(in_features=16, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=1))

In [144]:
# torch model_lr_1

In [145]:
print(model_lr_1)

Sequential(
  (0): Linear(in_features=40, out_features=16, bias=True)
  (1): ReLU()
  (2): Linear(in_features=16, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=32, bias=True)
  (7): ReLU()
  (8): Linear(in_features=32, out_features=32, bias=True)
  (9): ReLU()
  (10): Linear(in_features=32, out_features=1, bias=True)
)

In [146]:
# torch model_lr_1

In [147]:
metrics_name_2 = torch.nn.MSELoss()

In [148]:
# torch.nn.MSELoss()

In [149]:
Optimizer = optim.SGD(params=model_lr_1.parameters(), lr=0.0001)

In [150]:
# torch optimizer model_lr_1

In [151]:
BATCH_SIZE_LR_1 = 16

In [152]:
# torch batch

In [153]:
EPOCHS_LR_1 = 1000

In [154]:
# torch epochs

In [155]:
for epoch in tqdm.trange(EPOCHS_LR_1):
    for i in range((n_data - 1) // BATCH_SIZE_LR_1 + 1):
        start_i = i * BATCH_SIZE_LR_1
        end_i = start_i + BATCH_SIZE_LR_1
        Xb = X_train_tensor[start_i: end_i]
        yb = y_train_tensor[start_i: end_i]
        pred_2 = yb
        loss = loss_func(pred_2, yb + 1)

100%|███████████████████████████████████████| 1000/1000 [06:45<00:00,  2.47it/s]

In [156]:
# for epoch in tqdm.trange(EPOCHS_LR_1)

In [157]:
print(X_test)

[[ 2.14267765  0.039095    0.79884574 ...  0.89335901 -0.10884598
  -0.14702155]
 [ 0.64735879 -0.48534494 -0.66910215 ...  0.62880074  0.01611935
  -0.11988125]
 [-0.67204021  3.51946916 -0.21742588 ... -0.37652072 -0.03241087
  -0.37545239]
 ...
 [ 0.11959919 -0.67605037 -0.49972355 ... -0.3024444  -0.0591025
  -0.35283548]
 [-0.18826058 -0.48534494 -0.21742588 ... -0.39768538 -0.13371772
   1.35700334]
 [ 0.16357915 -0.67605037 -0.49972355 ... -0.37652072 -0.09671342
  -0.36188224]]

In [158]:
# X_test

In [159]:
print(y_test)

360511    39.3
392362    85.1
441510    20.2
106802    42.7
53         3.5
          ...
326281    20.1
64228      6.7
340331    20.1
1465       0.9
40621      9.8
Name: carbohydratecontent, Length: 156756, dtype: float64

In [160]:
# y_test

In [161]:
X = torch.randn(BATCH_SIZE_LR_1, 40)

In [162]:
# torch.randn()

In [163]:
y = torch.Tensor([[1.0], [0.0], [0.0], [1.0], [1.0],
    [1.0], [0.0], [0.0], [1.0], [1.0],
    [1.0], [0.0], [0.0], [1.0], [1.0],
    [1.0]])

In [164]:
# torch tensor

In [165]:
for epoch in range(1000):
    y_pred_3 = model_lr_1(X)
    loss = metrics_name_2(y_pred_3, y)
    print('epoch: ', epoch,' loss: ', loss.item())
    Optimizer.zero_grad()
    loss.backward()
    Optimizer.step()

epoch:  0  loss:  0.6660683155059814
epoch:  1  loss:  0.6657897233963013
epoch:  2  loss:  0.6655110120773315
epoch:  3  loss:  0.6652324795722961
epoch:  4  loss:  0.6649541854858398
epoch:  5  loss:  0.6646761894226074
epoch:  6  loss:  0.6643981337547302
epoch:  7  loss:  0.6641203761100769
epoch:  8  loss:  0.6638427972793579
epoch:  9  loss:  0.6635653376579285
epoch:  10  loss:  0.6632879972457886
epoch:  11  loss:  0.663010835647583
epoch:  12  loss:  0.6627339124679565
epoch:  13  loss:  0.6624569892883301
epoch:  14  loss:  0.6621804237365723
epoch:  15  loss:  0.6619038581848145
epoch:  16  loss:  0.6616275906562805
epoch:  17  loss:  0.6613515019416809
epoch:  18  loss:  0.6610755324363708
epoch:  19  loss:  0.6607997417449951
epoch:  20  loss:  0.6605240106582642
epoch:  21  loss:  0.6602485775947571
epoch:  22  loss:  0.6599732637405396
epoch:  23  loss:  0.6596980690956116
epoch:  24  loss:  0.6594230532646179
epoch:  25  loss:  0.6591482162475586
epoch:  26  loss:  0.6588736176490784
epoch:  27  loss:  0.6585990786552429
epoch:  28  loss:  0.6583247184753418
epoch:  29  loss:  0.6580505967140198
epoch:  30  loss:  0.6577765345573425
epoch:  31  loss:  0.6575027108192444
epoch:  32  loss:  0.657228946685791
epoch:  33  loss:  0.6569554209709167
epoch:  34  loss:  0.656682014465332
epoch:  35  loss:  0.6564089059829712
epoch:  36  loss:  0.6561357975006104
epoch:  37  loss:  0.6558630466461182
epoch:  38  loss:  0.6555901765823364
epoch:  39  loss:  0.6553177237510681
epoch:  40  loss:  0.6550452709197998
epoch:  41  loss:  0.6547731161117554
epoch:  42  loss:  0.6545010805130005
epoch:  43  loss:  0.6542291045188904
epoch:  44  loss:  0.6539574265480042
epoch:  45  loss:  0.6536857485771179
epoch:  46  loss:  0.6534143686294556
epoch:  47  loss:  0.6531431078910828
epoch:  48  loss:  0.6528719663619995
epoch:  49  loss:  0.6526010036468506
epoch:  50  loss:  0.6523303389549255
epoch:  51  loss:  0.6520597338676453
epoch:  52  loss:  0.6517893075942993
epoch:  53  loss:  0.6515189409255981
epoch:  54  loss:  0.6512488722801208
epoch:  55  loss:  0.6509789228439331
epoch:  56  loss:  0.6507090926170349
epoch:  57  loss:  0.6504395008087158
epoch:  58  loss:  0.6501700282096863
epoch:  59  loss:  0.6499006152153015
epoch:  60  loss:  0.6496314406394958
epoch:  61  loss:  0.6493625044822693
epoch:  62  loss:  0.6490936279296875
epoch:  63  loss:  0.64882493019104
epoch:  64  loss:  0.6485564112663269
epoch:  65  loss:  0.6482880711555481
epoch:  66  loss:  0.6480199098587036
epoch:  67  loss:  0.6477518081665039
epoch:  68  loss:  0.6474840044975281
epoch:  69  loss:  0.6472162008285522
epoch:  70  loss:  0.6469485759735107
epoch:  71  loss:  0.6466812491416931
epoch:  72  loss:  0.6464139223098755
epoch:  73  loss:  0.6461469531059265
epoch:  74  loss:  0.6458801031112671
epoch:  75  loss:  0.6456132531166077
epoch:  76  loss:  0.6453466415405273
epoch:  77  loss:  0.6450802087783813
epoch:  78  loss:  0.6448138952255249
epoch:  79  loss:  0.6445477604866028
epoch:  80  loss:  0.644281804561615
epoch:  81  loss:  0.6440160274505615
epoch:  82  loss:  0.6437503695487976
epoch:  83  loss:  0.6434848308563232
epoch:  84  loss:  0.643219530582428
epoch:  85  loss:  0.6429542303085327
epoch:  86  loss:  0.6426893472671509
epoch:  87  loss:  0.6424244046211243
epoch:  88  loss:  0.6421597003936768
epoch:  89  loss:  0.6418951749801636
epoch:  90  loss:  0.6416307687759399
epoch:  91  loss:  0.6413666009902954
epoch:  92  loss:  0.6411024332046509
epoch:  93  loss:  0.6408385038375854
epoch:  94  loss:  0.6405748128890991
epoch:  95  loss:  0.6403111815452576
epoch:  96  loss:  0.6400476098060608
epoch:  97  loss:  0.6397843956947327
epoch:  98  loss:  0.6395213007926941
epoch:  99  loss:  0.6392582654953003
epoch:  100  loss:  0.6389954686164856
epoch:  101  loss:  0.6387328505516052
epoch:  102  loss:  0.6384702324867249
epoch:  103  loss:  0.6382080316543579
epoch:  104  loss:  0.6379457712173462
epoch:  105  loss:  0.6376837491989136
epoch:  106  loss:  0.6374219059944153
epoch:  107  loss:  0.6371601223945618
epoch:  108  loss:  0.6368985772132874
epoch:  109  loss:  0.6366371512413025
epoch:  110  loss:  0.6363758444786072
epoch:  111  loss:  0.6361148357391357
epoch:  112  loss:  0.6358538866043091
epoch:  113  loss:  0.635593056678772
epoch:  114  loss:  0.635332465171814
epoch:  115  loss:  0.6350719928741455
epoch:  116  loss:  0.6348115801811218
epoch:  117  loss:  0.634551465511322
epoch:  118  loss:  0.6342914700508118
epoch:  119  loss:  0.6340315341949463
epoch:  120  loss:  0.6337718963623047
epoch:  121  loss:  0.6335123777389526
epoch:  122  loss:  0.6332529187202454
epoch:  123  loss:  0.6329936981201172
epoch:  124  loss:  0.6327345967292786
epoch:  125  loss:  0.6324756145477295
epoch:  126  loss:  0.6322168707847595
epoch:  127  loss:  0.6319582462310791
epoch:  128  loss:  0.631699800491333
epoch:  129  loss:  0.6314414739608765
epoch:  130  loss:  0.6311833262443542
epoch:  131  loss:  0.6309252381324768
epoch:  132  loss:  0.6306673884391785
epoch:  133  loss:  0.6304097771644592
epoch:  134  loss:  0.6301522850990295
epoch:  135  loss:  0.6298948526382446
epoch:  136  loss:  0.629637598991394
epoch:  137  loss:  0.6293805241584778
epoch:  138  loss:  0.6291235685348511
epoch:  139  loss:  0.6288667321205139
epoch:  140  loss:  0.6286101341247559
epoch:  141  loss:  0.6283535957336426
epoch:  142  loss:  0.6280973553657532
epoch:  143  loss:  0.6278411746025085
epoch:  144  loss:  0.6275851726531982
epoch:  145  loss:  0.6273293495178223
epoch:  146  loss:  0.6270736455917358
epoch:  147  loss:  0.626818060874939
epoch:  148  loss:  0.626562774181366
epoch:  149  loss:  0.6263075470924377
epoch:  150  loss:  0.6260524392127991
epoch:  151  loss:  0.6257975101470947
epoch:  152  loss:  0.6255427002906799
epoch:  153  loss:  0.6252881288528442
epoch:  154  loss:  0.6250336766242981
epoch:  155  loss:  0.6247793436050415
epoch:  156  loss:  0.6245251893997192
epoch:  157  loss:  0.6242710947990417
epoch:  158  loss:  0.6240172982215881
epoch:  159  loss:  0.6237635612487793
epoch:  160  loss:  0.6235100030899048
epoch:  161  loss:  0.6232565641403198
epoch:  162  loss:  0.623003363609314
epoch:  163  loss:  0.6227502822875977
epoch:  164  loss:  0.6224973201751709
epoch:  165  loss:  0.6222444772720337
epoch:  166  loss:  0.6219918131828308
epoch:  167  loss:  0.621739387512207
epoch:  168  loss:  0.621487021446228
epoch:  169  loss:  0.6212347745895386
epoch:  170  loss:  0.620982825756073
epoch:  171  loss:  0.6207308769226074
epoch:  172  loss:  0.6204791069030762
epoch:  173  loss:  0.6202275156974792
epoch:  174  loss:  0.6199760437011719
epoch:  175  loss:  0.6197248101234436
epoch:  176  loss:  0.6194736957550049
epoch:  177  loss:  0.6192226409912109
epoch:  178  loss:  0.6189718246459961
epoch:  179  loss:  0.618721067905426
epoch:  180  loss:  0.6184705495834351
epoch:  181  loss:  0.6182200908660889
epoch:  182  loss:  0.6179699301719666
epoch:  183  loss:  0.6177197694778442
epoch:  184  loss:  0.6174699068069458
epoch:  185  loss:  0.6172200441360474
epoch:  186  loss:  0.6169703602790833
epoch:  187  loss:  0.6167208552360535
epoch:  188  loss:  0.6164715886116028
epoch:  189  loss:  0.6162223219871521
epoch:  190  loss:  0.6159733533859253
epoch:  191  loss:  0.6157243847846985
epoch:  192  loss:  0.615475594997406
epoch:  193  loss:  0.6152269840240479
epoch:  194  loss:  0.614978551864624
epoch:  195  loss:  0.6147302389144897
epoch:  196  loss:  0.6144821047782898
epoch:  197  loss:  0.6142340898513794
epoch:  198  loss:  0.6139861345291138
epoch:  199  loss:  0.613738477230072
epoch:  200  loss:  0.613490879535675
epoch:  201  loss:  0.6132434606552124
epoch:  202  loss:  0.6129962205886841
epoch:  203  loss:  0.6127490401268005
epoch:  204  loss:  0.6125020384788513
epoch:  205  loss:  0.6122552156448364
epoch:  206  loss:  0.6120085120201111
epoch:  207  loss:  0.6117619872093201
epoch:  208  loss:  0.6115155816078186
epoch:  209  loss:  0.6112693548202515
epoch:  210  loss:  0.6110232472419739
epoch:  211  loss:  0.6107773780822754
epoch:  212  loss:  0.6105315089225769
epoch:  213  loss:  0.6102858185768127
epoch:  214  loss:  0.6100403070449829
epoch:  215  loss:  0.6097949743270874
epoch:  216  loss:  0.6095497608184814
epoch:  217  loss:  0.6093047261238098
epoch:  218  loss:  0.6090598106384277
epoch:  219  loss:  0.60881507396698
epoch:  220  loss:  0.6085703372955322
epoch:  221  loss:  0.6083258986473083
epoch:  222  loss:  0.6080815196037292
epoch:  223  loss:  0.6078373789787292
epoch:  224  loss:  0.607593297958374
epoch:  225  loss:  0.6073493957519531
epoch:  226  loss:  0.6071056127548218
epoch:  227  loss:  0.6068620681762695
epoch:  228  loss:  0.6066185832023621
epoch:  229  loss:  0.6063752770423889
epoch:  230  loss:  0.6061320900917053
epoch:  231  loss:  0.605889081954956
epoch:  232  loss:  0.6056462526321411
epoch:  233  loss:  0.605403482913971
epoch:  234  loss:  0.6051608324050903
epoch:  235  loss:  0.6049184203147888
epoch:  236  loss:  0.6046761274337769
epoch:  237  loss:  0.6044339537620544
epoch:  238  loss:  0.6041919589042664
epoch:  239  loss:  0.6039500832557678
epoch:  240  loss:  0.6037083864212036
epoch:  241  loss:  0.6034667491912842
epoch:  242  loss:  0.6032253503799438
epoch:  243  loss:  0.6029840707778931
epoch:  244  loss:  0.6027429103851318
epoch:  245  loss:  0.6025019288063049
epoch:  246  loss:  0.6022610068321228
epoch:  247  loss:  0.6020203232765198
epoch:  248  loss:  0.6017798185348511
epoch:  249  loss:  0.6015393733978271
epoch:  250  loss:  0.6012991070747375
epoch:  251  loss:  0.6010589599609375
epoch:  252  loss:  0.600818932056427
epoch:  253  loss:  0.600579023361206
epoch:  254  loss:  0.6003393530845642
epoch:  255  loss:  0.6000998616218567
epoch:  256  loss:  0.5998603701591492
epoch:  257  loss:  0.5996211171150208
epoch:  258  loss:  0.5993819832801819
epoch:  259  loss:  0.5991429686546326
epoch:  260  loss:  0.5989041328430176
epoch:  261  loss:  0.5986654758453369
epoch:  262  loss:  0.598426878452301
epoch:  263  loss:  0.5981884002685547
epoch:  264  loss:  0.5979501605033875
epoch:  265  loss:  0.5977120399475098
epoch:  266  loss:  0.5974739789962769
epoch:  267  loss:  0.5972362160682678
epoch:  268  loss:  0.5969984531402588
epoch:  269  loss:  0.5967608690261841
epoch:  270  loss:  0.5965234041213989
epoch:  271  loss:  0.5962862372398376
epoch:  272  loss:  0.5960490107536316
epoch:  273  loss:  0.5958120822906494
epoch:  274  loss:  0.5955751538276672
epoch:  275  loss:  0.5953384637832642
epoch:  276  loss:  0.5951018929481506
epoch:  277  loss:  0.5948654413223267
epoch:  278  loss:  0.594629168510437
epoch:  279  loss:  0.5943930149078369
epoch:  280  loss:  0.5941569805145264
epoch:  281  loss:  0.5939211249351501
epoch:  282  loss:  0.5936853885650635
epoch:  283  loss:  0.5934498310089111
epoch:  284  loss:  0.5932143330574036
epoch:  285  loss:  0.5929790735244751
epoch:  286  loss:  0.5927439332008362
epoch:  287  loss:  0.5925089120864868
epoch:  288  loss:  0.592274010181427
epoch:  289  loss:  0.5920392870903015
epoch:  290  loss:  0.5918046236038208
epoch:  291  loss:  0.591570258140564
epoch:  292  loss:  0.5913358926773071
epoch:  293  loss:  0.5911017060279846
epoch:  294  loss:  0.5908676981925964
epoch:  295  loss:  0.5906338095664978
epoch:  296  loss:  0.5904000401496887
epoch:  297  loss:  0.5901663899421692
epoch:  298  loss:  0.589932918548584
epoch:  299  loss:  0.5896995663642883
epoch:  300  loss:  0.5894664525985718
epoch:  301  loss:  0.5892332792282104
epoch:  302  loss:  0.589000403881073
epoch:  303  loss:  0.5887676477432251
epoch:  304  loss:  0.588534951210022
epoch:  305  loss:  0.588302493095398
epoch:  306  loss:  0.5880700945854187
epoch:  307  loss:  0.5878379344940186
epoch:  308  loss:  0.5876057744026184
epoch:  309  loss:  0.5873737931251526
epoch:  310  loss:  0.5871419906616211
epoch:  311  loss:  0.5869103670120239
epoch:  312  loss:  0.5866788029670715
epoch:  313  loss:  0.5864474177360535
epoch:  314  loss:  0.586216151714325
epoch:  315  loss:  0.5859850645065308
epoch:  316  loss:  0.5857540965080261
epoch:  317  loss:  0.585523247718811
epoch:  318  loss:  0.5852925777435303
epoch:  319  loss:  0.5850620269775391
epoch:  320  loss:  0.5848315954208374
epoch:  321  loss:  0.5846012830734253
epoch:  322  loss:  0.5843711495399475
epoch:  323  loss:  0.5841411352157593
epoch:  324  loss:  0.5839112401008606
epoch:  325  loss:  0.5836815237998962
epoch:  326  loss:  0.5834519863128662
epoch:  327  loss:  0.5832224488258362
epoch:  328  loss:  0.58299320936203
epoch:  329  loss:  0.5827639698982239
epoch:  330  loss:  0.5825348496437073
epoch:  331  loss:  0.5823060274124146
epoch:  332  loss:  0.5820772051811218
epoch:  333  loss:  0.5818485617637634
epoch:  334  loss:  0.5816200375556946
epoch:  335  loss:  0.5813917517662048
epoch:  336  loss:  0.5811635255813599
epoch:  337  loss:  0.5809354186058044
epoch:  338  loss:  0.5807074308395386
epoch:  339  loss:  0.580479621887207
epoch:  340  loss:  0.580251932144165
epoch:  341  loss:  0.5800244212150574
epoch:  342  loss:  0.5797970294952393
epoch:  343  loss:  0.5795698165893555
epoch:  344  loss:  0.5793426036834717
epoch:  345  loss:  0.579115629196167
epoch:  346  loss:  0.5788887739181519
epoch:  347  loss:  0.5786620378494263
epoch:  348  loss:  0.5784354209899902
epoch:  349  loss:  0.5782090425491333
epoch:  350  loss:  0.5779826045036316
epoch:  351  loss:  0.5777563452720642
epoch:  352  loss:  0.5775302052497864
epoch:  353  loss:  0.5773040652275085
epoch:  354  loss:  0.5770781636238098
epoch:  355  loss:  0.5768523812294006
epoch:  356  loss:  0.576626718044281
epoch:  357  loss:  0.5764012336730957
epoch:  358  loss:  0.5761758685112
epoch:  359  loss:  0.5759506225585938
epoch:  360  loss:  0.5757255554199219
epoch:  361  loss:  0.5755005478858948
epoch:  362  loss:  0.5752756595611572
epoch:  363  loss:  0.5750510096549988
epoch:  364  loss:  0.5748264193534851
epoch:  365  loss:  0.5746020078659058
epoch:  366  loss:  0.574377715587616
epoch:  367  loss:  0.5741535425186157
epoch:  368  loss:  0.573929488658905
epoch:  369  loss:  0.5737056136131287
epoch:  370  loss:  0.5734818577766418
epoch:  371  loss:  0.5732582807540894
epoch:  372  loss:  0.5730347633361816
epoch:  373  loss:  0.5728113651275635
epoch:  374  loss:  0.5725881457328796
epoch:  375  loss:  0.5723651647567749
epoch:  376  loss:  0.5721421241760254
epoch:  377  loss:  0.571919322013855
epoch:  378  loss:  0.5716966390609741
epoch:  379  loss:  0.5714741349220276
epoch:  380  loss:  0.5712516903877258
epoch:  381  loss:  0.5710293650627136
epoch:  382  loss:  0.5708072185516357
epoch:  383  loss:  0.5705851912498474
epoch:  384  loss:  0.5703633427619934
epoch:  385  loss:  0.5701415538787842
epoch:  386  loss:  0.5699199438095093
epoch:  387  loss:  0.5696984529495239
epoch:  388  loss:  0.5694770812988281
epoch:  389  loss:  0.5692558884620667
epoch:  390  loss:  0.56903475522995
epoch:  391  loss:  0.5688138008117676
epoch:  392  loss:  0.5685929656028748
epoch:  393  loss:  0.5683723092079163
epoch:  394  loss:  0.5681517720222473
epoch:  395  loss:  0.5679312944412231
epoch:  396  loss:  0.5677109956741333
epoch:  397  loss:  0.5674908757209778
epoch:  398  loss:  0.567270815372467
epoch:  399  loss:  0.5670508742332458
epoch:  400  loss:  0.566831111907959
epoch:  401  loss:  0.5666115283966064
epoch:  402  loss:  0.5663920640945435
epoch:  403  loss:  0.5661726593971252
epoch:  404  loss:  0.5659534335136414
epoch:  405  loss:  0.565734326839447
epoch:  406  loss:  0.565515398979187
epoch:  407  loss:  0.5652965307235718
epoch:  408  loss:  0.5650777816772461
epoch:  409  loss:  0.5648592710494995
epoch:  410  loss:  0.5646407604217529
epoch:  411  loss:  0.5644224286079407
epoch:  412  loss:  0.5642042756080627
epoch:  413  loss:  0.5639862418174744
epoch:  414  loss:  0.5637683272361755
epoch:  415  loss:  0.5635505318641663
epoch:  416  loss:  0.5633328557014465
epoch:  417  loss:  0.5631152987480164
epoch:  418  loss:  0.5628979206085205
epoch:  419  loss:  0.5626806616783142
epoch:  420  loss:  0.5624635219573975
epoch:  421  loss:  0.5622465014457703
epoch:  422  loss:  0.5620296597480774
epoch:  423  loss:  0.5618128776550293
epoch:  424  loss:  0.5615962147712708
epoch:  425  loss:  0.5613797903060913
epoch:  426  loss:  0.5611633658409119
epoch:  427  loss:  0.5609471201896667
epoch:  428  loss:  0.560731053352356
epoch:  429  loss:  0.5605151653289795
epoch:  430  loss:  0.560299277305603
epoch:  431  loss:  0.5600835084915161
epoch:  432  loss:  0.5598679780960083
epoch:  433  loss:  0.55965256690979
epoch:  434  loss:  0.5594372153282166
epoch:  435  loss:  0.5592219829559326
epoch:  436  loss:  0.5590069890022278
epoch:  437  loss:  0.5587920546531677
epoch:  438  loss:  0.5585772395133972
epoch:  439  loss:  0.558362603187561
epoch:  440  loss:  0.5581480860710144
epoch:  441  loss:  0.5579335689544678
epoch:  442  loss:  0.557719349861145
epoch:  443  loss:  0.5575051307678223
epoch:  444  loss:  0.5572911500930786
epoch:  445  loss:  0.5570772290229797
epoch:  446  loss:  0.5568634867668152
epoch:  447  loss:  0.5566498041152954
epoch:  448  loss:  0.55643630027771
epoch:  449  loss:  0.5562229156494141
epoch:  450  loss:  0.5560095906257629
epoch:  451  loss:  0.5557965040206909
epoch:  452  loss:  0.5555835366249084
epoch:  453  loss:  0.555370569229126
epoch:  454  loss:  0.5551578998565674
epoch:  455  loss:  0.5549452304840088
epoch:  456  loss:  0.5547327995300293
epoch:  457  loss:  0.5545204281806946
epoch:  458  loss:  0.5543081760406494
epoch:  459  loss:  0.5540961027145386
epoch:  460  loss:  0.5538841485977173
epoch:  461  loss:  0.5536722540855408
epoch:  462  loss:  0.5534605383872986
epoch:  463  loss:  0.5532490015029907
epoch:  464  loss:  0.5530375242233276
epoch:  465  loss:  0.5528262257575989
epoch:  466  loss:  0.5526149868965149
epoch:  467  loss:  0.5524039268493652
epoch:  468  loss:  0.5521929860115051
epoch:  469  loss:  0.5519822239875793
epoch:  470  loss:  0.5517714619636536
epoch:  471  loss:  0.5515608787536621
epoch:  472  loss:  0.5513504147529602
epoch:  473  loss:  0.5511401295661926
epoch:  474  loss:  0.5509299635887146
epoch:  475  loss:  0.5507198572158813
epoch:  476  loss:  0.5505099892616272
epoch:  477  loss:  0.550300121307373
epoch:  478  loss:  0.5500904321670532
epoch:  479  loss:  0.549880862236023
epoch:  480  loss:  0.549671471118927
epoch:  481  loss:  0.5494621396064758
epoch:  482  loss:  0.5492529273033142
epoch:  483  loss:  0.5490438342094421
epoch:  484  loss:  0.5488349199295044
epoch:  485  loss:  0.5486261248588562
epoch:  486  loss:  0.5484174489974976
epoch:  487  loss:  0.5482088327407837
epoch:  488  loss:  0.5480004549026489
epoch:  489  loss:  0.5477921366691589
epoch:  490  loss:  0.5475839972496033
epoch:  491  loss:  0.5473759174346924
epoch:  492  loss:  0.5471680164337158
epoch:  493  loss:  0.5469602346420288
epoch:  494  loss:  0.5467525720596313
epoch:  495  loss:  0.5465449690818787
epoch:  496  loss:  0.5463376045227051
epoch:  497  loss:  0.5461302995681763
epoch:  498  loss:  0.545923113822937
epoch:  499  loss:  0.5457160472869873
epoch:  500  loss:  0.5455090999603271
epoch:  501  loss:  0.5453022718429565
epoch:  502  loss:  0.5450956225395203
epoch:  503  loss:  0.5448891520500183
epoch:  504  loss:  0.5446827411651611
epoch:  505  loss:  0.5444763898849487
epoch:  506  loss:  0.5442701578140259
epoch:  507  loss:  0.5440641641616821
epoch:  508  loss:  0.5438582301139832
epoch:  509  loss:  0.543652355670929
epoch:  510  loss:  0.5434467196464539
epoch:  511  loss:  0.5432412028312683
epoch:  512  loss:  0.5430357456207275
epoch:  513  loss:  0.5428304672241211
epoch:  514  loss:  0.5426252484321594
epoch:  515  loss:  0.5424201488494873
epoch:  516  loss:  0.5422152876853943

In [166]:
# for epoch in range(1000)

In [167]:
def train_1(model_lr_1, loss_fn, optimizer):
    """function_1 train_1"""
    size = len(X_train_tensor)
    model_lr_1.train()
    for batch_size_lr_1 in range(1000):
        y_pred_4 = model_lr_1(X)
        loss = loss_fn(y_pred_4, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if BATCH_SIZE_LR_1 % 16 == 0:
            loss_3 = loss.item(), BATCH_SIZE_LR * len(X)
            print(f'loss: {loss_3}')

In [168]:
# function_1 train_1

In [169]:
def test_1(model_lr_1, loss_fn):
    """function_1 test_1"""
    size = len(X_train_tensor)
    num_batches = size
    model_lr_1.eval()
    test_loss = 0
    with torch.no_grad():
        for batch_size_lr_1 in range(1000):
            y_pred_5 = model_lr_1(X)
            test_loss += loss_fn(y_pred_5, y).item()
            test_loss /= num_batches
            print(f'Test loss: {test_loss}')

In [170]:
# function_1 test_1

In [171]:
with torch.no_grad():
    print(model_lr_1(X_test_tensor[-1:]))

tensor([[0.1497]])

In [172]:
# X_test_tensor[-1:]

In [173]:
torch.save(model_lr_1, "lr_1.pth")

In [174]:
# torch.save(model_lr_1)